/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator_app;

/**
 *
 * @author Charitha Dasanayake
 */
public class ycalculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    double num1, num2;
    int cal, se;
    boolean counter, minus, activeoperators, dotpress, afterequal;
    String screennumber, textconvert;

    public ycalculator() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        cButton = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        epualButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        minusButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        additionButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        additionButton.setText("+");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        subtractionButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        subtractionButton.setText("-");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        fourButton.setText("4");
        fourButton.setToolTipText("");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        multiplicationButton.setText("*");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        divideButton.setText("/");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        dotButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        dotButton.setText(".");
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        epualButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        epualButton.setText("=");
        epualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epualButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        clearButton.setText("<--");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 51, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        minusButton1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        minusButton1.setText("+/-");
        minusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(minusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(epualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        screennumber = jTextField1.getText().replaceAll(",", "");
        int v1 = screennumber.length();
        int v2 = screennumber.length() - 1;
        String store;

        if (v1 > 0) {
            StringBuilder type = new StringBuilder(screennumber);
            type.deleteCharAt(v2);
            store = type.toString();
            jTextField1.setText(intext(store));
        }
        if (v1 <= 1) {
            jTextField1.setText("0");
            screennumber = "";
            se = 0;
        }

    }//GEN-LAST:event_clearButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        nextround();

        if (jTextField1.getText().length() <= 20) {
            if (jTextField1.getText().length() == 1 && jTextField1.getText().contains("0")) {

            } else {
                screennumber = (jTextField1.getText() + "0");
                if (screennumber.contains("-")) {
                    jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
                } else {
                    jTextField1.setText(intext(screennumber));
                }
            }
        }

    }//GEN-LAST:event_zeroButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "1");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }

        }
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "2");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "3");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_threeButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "4");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "5");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "6");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_sixButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "7");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "8");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        nextround();
        if (jTextField1.getText().length() <= 19) {
            screennumber = (jTextField1.getText() + "9");
            if (screennumber.contains("-")) {
                jTextField1.setText("-" + intext(screennumber.replaceAll("-", "")));
            } else {
                jTextField1.setText(intext(screennumber));
            }
        }
    }//GEN-LAST:event_nineButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        if (afterequal == true) {

        } else {

            if (jTextField1.getText().length() == 1 && jTextField1.getText().contains("-")) {

            } else if (!(jTextField1.getText().contains("."))) {
                jTextField1.setText(jTextField1.getText() + ".");
            }
            dotpress = true;

        }
    }//GEN-LAST:event_dotButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed

        if (jTextField2.getText().length() > 0) {
            secondcalculation();

        } else {

            num1 = Double.parseDouble(jTextField1.getText().replaceAll(",", ""));

        }
        String value2 = Double.toString(num1);
        char c1 = value2.charAt(value2.length() - 1);
        char c2 = value2.charAt(value2.length() - 2);
        if (c1 == '0' && c2 == '.') {
            int num4 = (int) num1;
            jTextField2.setText(intext(String.valueOf(num4)) + " + ");
            num1 = num4;
        } else {
            jTextField2.setText(intext(value2) + " + ");
        }

        cal = 1;
        jTextField1.setText("0");
        screennumber = "";
        se = 0;
        activeoperators = true;

    }//GEN-LAST:event_additionButtonActionPerformed

    private void epualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epualButtonActionPerformed
        if (activeoperators == true) {
            calculation();
            counter = true;
            minus = false;
            jTextField2.setText("");
            activeoperators = false;
        }

    }//GEN-LAST:event_epualButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        jTextField1.setText("0");
        screennumber = "";
        jTextField2.setText("");
        se = 0;
        minus = false;
    }//GEN-LAST:event_cButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        if (jTextField2.getText().length() > 0) {
            secondcalculation();
        } else {
            num1 = Double.parseDouble(jTextField1.getText().replaceAll(",", ""));

        }
        jTextField1.setText("0");
        String value2 = Double.toString(num1);
        char c1 = value2.charAt(value2.length() - 1);
        char c2 = value2.charAt(value2.length() - 2);
        if (c1 == '0' && c2 == '.') {
            int num4 = (int) num1;
            jTextField2.setText(intext(String.valueOf(num4)) + " - ");
            num1 = num4;
        } else {
            jTextField2.setText(intext(value2) + " - ");
        }
        cal = 2;
        jTextField1.setText("0");
        screennumber = "";
        se = 0;
        activeoperators = true;
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        if (jTextField2.getText().length() > 0) {
            secondcalculation();
        } else {
            num1 = Double.parseDouble(jTextField1.getText().replaceAll(",", ""));

        }
        jTextField1.setText("0");
        String value2 = Double.toString(num1);
        char c1 = value2.charAt(value2.length() - 1);
        char c2 = value2.charAt(value2.length() - 2);
        if (c1 == '0' && c2 == '.') {
            int num4 = (int) num1;
            jTextField2.setText(intext(String.valueOf(num4)) + " * ");
            num1 = num4;
        } else {
            jTextField2.setText(intext(value2) + " * ");
        }
        cal = 3;
        jTextField1.setText("0");
        screennumber = "";
        se = 0;
        activeoperators = true;
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        if (jTextField2.getText().length() > 0) {
            secondcalculation();

        } else {
            num1 = Double.parseDouble(jTextField1.getText().replaceAll(",", ""));

        }
        jTextField1.setText("0");
        String value2 = Double.toString(num1);
        char c1 = value2.charAt(value2.length() - 1);
        char c2 = value2.charAt(value2.length() - 2);
        if (c1 == '0' && c2 == '.') {
            int num4 = (int) num1;
            jTextField2.setText(intext(String.valueOf(num4)) + " / ");
            num1 = num4;
        } else {
            jTextField2.setText(intext(value2) + " / ");
        }
        cal = 4;
        jTextField1.setText("0");
        screennumber = "";
        se = 0;
        activeoperators = true;
    }//GEN-LAST:event_divideButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void minusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButton1ActionPerformed
        if (minus == true) {
            jTextField1.setText("0");
            screennumber = "";
            minus = false;
        } else {
            char m1 = jTextField1.getText().charAt(jTextField1.getText().length() - 1);
            if (jTextField1.getText().length() == 1 && m1 == '0') {
                jTextField1.setText("-0");
                minus = true;
            }
        }

    }//GEN-LAST:event_minusButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ycalculator().setVisible(true);
        });
    }

    public void calculation() {
        afterequal = true;
        switch (cal) {

            case 1:
                num2 = num1 + Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
                break;

            case 2:
                num2 = num1 - Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
                break;

            case 3:
                num2 = num1 * Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
                break;

            case 4:
                num2 = num1 / Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
                break;

        }
        String value1 = Double.toString(num2);
        char c1 = value1.charAt(value1.length() - 1);
        char c2 = value1.charAt(value1.length() - 2);
        if (c1 == '0' && c2 == '.') {
            int num3 = (int) num2;
            jTextField1.setText(intext(String.valueOf(num3)));
        } else {
            jTextField1.setText(intext(Double.toString(num2)));
        }

    }

    public void secondcalculation() {

        if (jTextField2.getText().contains("+")) {
            num1 = num1 + Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
        } else if (jTextField2.getText().contains("-")) {
            num1 = num1 - Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
        } else if (jTextField2.getText().contains("*")) {
            num1 = num1 * Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
        } else if (jTextField2.getText().contains("/")) {
            num1 = num1 / Double.parseDouble(jTextField1.getText().replaceAll(",", ""));
        }

    }

    public void nextround() {
        /* counter for '=' button press ==> counter=true;
           se for operation buttons and clear button ==> se=0;
           minus for minus button */
        afterequal = false;
        if (dotpress == false) {
            if (counter || (se == 0)) {
                if (minus == true) {
                    jTextField1.setText("-");
                    minus = false;
                } else {
                    jTextField1.setText("");
                }
                counter = false;
            }

        }
        if (jTextField1.getText().length() == 1 && jTextField1.getText().contains("0")) {
            jTextField1.setText("");
        }
        dotpress = false;
        se++;
    }

    public static String intext(String in) {  //pass screen number

        String activity1 = in.replaceAll(",", "");

        if (activity1.contains(".")) {

            int dotposition = activity1.indexOf(".");
            String beforedot = activity1.substring(0, dotposition);
            String afterdot = activity1.substring(dotposition);

            String activity2 = secondindex(beforedot) + afterdot;
            return activity2;

        } else {
            return secondindex(activity1);

        }
        //return secondindex(activity1);
    }

    public static String secondindex(String in2) {
        String str = in2;
        StringBuilder threedigi = new StringBuilder(str);
        if (str.length() > 3) {
            if (str.length() <= 6) {
                threedigi.insert(str.length() - 3, ',');
            } else if (str.length() > 6 && str.length() <= 9) {
                threedigi.insert(threedigi.length() - 6, ',');
                if (threedigi.length() <= 10) {
                    threedigi.insert(threedigi.length() - 3, ',');
                }
            } else if (str.length() > 9 && str.length() <= 12) {
                threedigi.insert(threedigi.length() - 9, ',');
                if (threedigi.length() <= 13) {
                    threedigi.insert(threedigi.length() - 6, ',');
                    if (threedigi.length() <= 14) {
                        threedigi.insert(threedigi.length() - 3, ',');
                    }
                }
            } else if (str.length() > 12 && str.length() <= 15) {
                threedigi.insert(threedigi.length() - 12, ',');
                if (threedigi.length() <= 16) {
                    threedigi.insert(threedigi.length() - 9, ',');
                    if (threedigi.length() <= 17) {
                        threedigi.insert(threedigi.length() - 6, ',');
                        if (threedigi.length() <= 18) {
                            threedigi.insert(threedigi.length() - 3, ',');
                        }
                    }
                }
            } else if (str.length() > 15 && str.length() <= 18) {
                threedigi.insert(threedigi.length() - 15, ',');
                if (threedigi.length() <= 19) {
                    threedigi.insert(threedigi.length() - 12, ',');
                    if (threedigi.length() <= 20) {
                        threedigi.insert(threedigi.length() - 9, ',');
                        if (threedigi.length() <= 21) {
                            threedigi.insert(threedigi.length() - 6, ',');
                            if (threedigi.length() <= 22) {
                                threedigi.insert(threedigi.length() - 3, ',');
                            }
                        }
                    }
                }
            } else if (str.length() > 18 && str.length() <= 20) {
                threedigi.insert(threedigi.length() - 18, ',');
                if (threedigi.length() <= 21) {
                    threedigi.insert(threedigi.length() - 15, ',');
                    if (threedigi.length() <= 22) {
                        threedigi.insert(threedigi.length() - 12, ',');
                        if (threedigi.length() <= 23) {
                            threedigi.insert(threedigi.length() - 9, ',');
                            if (threedigi.length() <= 24) {
                                threedigi.insert(threedigi.length() - 6, ',');
                                if (threedigi.length() <= 25) {
                                    threedigi.insert(threedigi.length() - 3, ',');
                                }
                            }
                        }
                    }
                }
            }
        }
        str = threedigi.toString();
        return str;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton epualButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton minusButton1;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
